apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.recruitmentApp.name }}
  labels:
    {{- include "recruitment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.recruitmentApp.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.recruitmentApp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.recruitmentApp.name }}
    spec:
      containers:
        - name: recruitment-app
          image: "{{ .Values.recruitmentApp.image.repository }}:{{ .Values.recruitmentApp.image.tag }}"
          ports:
            - containerPort: {{ .Values.recruitmentApp.containerPort }}

          env:
            - name: MONGO_URL
              value: {{ .Values.recruitmentApp.env.MONGO_URL | quote }}
            - name: NODE_ENV
              value: {{ .Values.recruitmentApp.env.NODE_ENV | quote }}
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.recruitmentApp.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.recruitmentApp.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
