apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.name }}
spec:
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          ports:
            - containerPort: {{ .Values.mongodb.containerPort }}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-storage
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: {{ .Values.mongodb.pvc.name }}

