apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  init.js: |
    db = db.getSiblingDB("hr_system");
    db.createUser({
      user: "hrapp",
      pwd: "hrapp123",
      roles: [{ role: "readWrite", db: "hr_system" }]
    });
