apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.mongodb.service.name }}
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          ports:
            - containerPort: {{ .Values.mongodb.containerPort }}
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes:
          - {{ .Values.mongodb.pvc.accessMode }}
        storageClassName: {{ .Values.mongodb.pvc.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.mongodb.pvc.size }}
