apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.recruitmentApp.service.name }}
spec:
  type: {{ .Values.recruitmentApp.service.type }}
  selector:
    app: {{ .Values.recruitmentApp.name }}
  ports:
    - port: {{ .Values.recruitmentApp.service.port }}
      targetPort: {{ .Values.recruitmentApp.service.targetPort }}

